---
kind: pipeline
type: docker
name: default

steps:
- name: build-docker-image
  image: reg-01.ogilvie.us/app
  commands:
    - echo Building image
  when:
    event: 
      - push
    branch:
      - master
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password

