---
kind: pipeline
name: build 
type: docker

trigger:
  event:
    exclude:
      - tag

steps:

- name: build
  image: reg-01.ogilvie.us/app
  settings:
    debug: true
    repo: aco950/app
    registry: reg-01.ogilvie.us

  commands:
    - echo Building Image

  when:
    event:
      exclude:
        - tag 
