---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: app:latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  commands:
    - echo Building Image
  when:
    event:
      - push
    branch:
      - master

