---
kind: pipeline
name: build 
type: docker

steps:
- name: build
  image: reg-01.ogilvie.us/app
  settings:
    #username: username
    #password: password
    debug: true
    repo: aco950/app
    registry: reg-01.ogilvie.us

  commands:
    - echo Building Image

  when:
    event:
      exclude:
        - tag 


---
kind: pipeline
name: deploy

steps:
  - name: nomad 
    image: loq9/drone-nomad
    settings:
      addr: http://192.168.4.91:4647
      template: app.nomad

