---
kind: pipeline
type: docker
name: default

steps:
- name: build-docker-image
  image: plugins/docker
  commands:
    - echo Building image
  when:
    event: 
      - push
    branch:
      - master
  settings:
    repo: aco950/app
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

