---
kind: pipeline
name: build 

# Do not start any builds if we are only doing tags:
trigger:
  event:
    exclude:
      - tag

steps:

- name: build
  image: plugins/docker
  settings:
    debug: true
    repo: reg-01.ogilvie.us/aco950/app
    registry: reg-01.ogilvie.us

